title: David Dawes
bio: Video editor with a strong background in lifestyle content, reality television, and documentary editing. Skilled in storytelling, pacing, and technical execution across multiple genres, including home renovation, cooking, lifestyle programming, and feature films. Proven ability to manage tight deadlines and collaborate with producers and directors to shape narratives and deliver engaging content for national broadcast and streaming platforms.
logo: /assets/img/headshot.png
descriptions: Digital Media Editor/producer
email: attractormedia@gmail.com
github: https://github.com/AttractorMedia
linkedin: https://www.linkedin.com/in/daviddawes/
huggingface: https://huggingface.co/Ddawes

# show_downloads: true
theme: jekyll-theme-minimal
vimeoId: 4119605
