author: true
author.name: David Dawes
logo: /assets/img/headshot.jpeg
experience: Video editor, Digital Media, Ai content producer
#links:
#email: attractormedia@gmail.com
#labels: "Hugging Face"
#url: "https://huggingface.co/Ddawes"
#icons: "fa-regular fa-face-smiling-hands"
#labels: "Github"
#icons: "fab fa-fw fa-github"  # Corrected: Put icons here
#url: "https://github.com/AttractorMedia"
#labels: "LinkedIn"  # Corrected: Corrected the spelling
#icons: "fa-brands fa-linkedin" # Corrected: Put icons here
#url: "https://www.linkedin.com/in/daviddawes"
#theme: jekyll-theme-midnight
remote_theme: sharu725/online-cv #Remove this, as you are using a local theme.
theme_skin: orange #Remove this, as you are using a local theme.
#remote_theme: mmistakes/minimal-mistakes #Remove this, as you are using a local theme.
#minimal_mistakes_skin: dark #Remove this, as you are using a local theme.
#vimeoId: 4120329
