title: David Dawes
logo: /assets/img/headshot.png
descriptions: Digital Media Editor/producer
email: attractormedia@gmail.com
github: https://github.com/AttractorMedia
linkedin: https://www.linkedin.com/in/daviddawes/
huggingface: https://huggingface.co/Ddawes
# show_downloads: true
theme: jekyll-theme-minimal
vimeoId: 4119605
