title: David Dawes
logo: /assets/img/headshot.png
bio: Video editor with a strong background in lifestyle content, reality television, and documentary editing. 
     Skilled in storytelling, pacing, and technical execution across multiple genres.
descriptions: Digital Media Editor/producer
email: attractormedia@gmail.com
github: https://github.com/AttractorMedia
linkedin: https://www.linkedin.com/in/daviddawes/
huggingface: https://huggingface.co/Ddawes
#remote_theme: sharu725/online-cv
theme: jekyll-theme-Minimal
#theme_skin: orange
vimeoId: 4119605
