author: David Dawes
  logo: "/assets/img/headshot.jpeg"
  Experience: Video editor with a strong background in lifestyle content, reality television, 
              and documentary editing. Skilled in storytelling, pacing, and technical execution 
              across multiple genres, including home renovation, cooking, lifestyle programming, 
              and feature films. Proven ability to manage tight deadlines and collaborate with producers 
              and directors to shape narratives and  deliver engaging content for national broadcast 
              and streaming platforms.
  links:
    - labels: "phone"
      url: "(310) 739-8643"
    - labels: "email"
      url: "attractormedia@gmail.com"
    - labels: "Hugging Face"
      url: "https://huggingface.co/Ddawes"
    - labels: "Github"
      icons: "fa-brands fa-github"  # Corrected: Put icons here
      url: "https://github.com/AttractorMedia"
    - labels: "LinkedIn"  # Corrected: Corrected the spelling
      icons: "fa-brands fa-linkedin" # Corrected: Put icons here
      url: "https://www.linkedin.com/in/daviddawes"
theme: jekyll-theme-minimal
#remote_theme: sharu725/online-cv #Remove this, as you are using a local theme.
#theme_skin: orange #Remove this, as you are using a local theme.
#remote_theme: mmistakes/minimal-mistakes #Remove this, as you are using a local theme.
#minimal_mistakes_skin: dark #Remove this, as you are using a local theme.
#vimeoId: 4120329
